apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testing-apache-aws-praven"
  labels:
    system: web-apps
    trackid: aws-apache-web-app-20231005140155
  links:
    - url: https://github.com/RohanAwasthi/aws-apache-web-app
      title: "testing-apache-aws-praven"
      icon: code
  tags:
    - java
    - aws
    - applicationtype-webapplication
  annotations:
    jenkins.io/github-folder: 'apache-aws-web-app/testing-apache-aws-praven'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: 'RohanAwasthi/aws-apache-web-app'
    sonarqube.org/project-key: 'JtSpringProject/rachit'
   # prometheus.io/rules: './prometheus-rule.yaml'
    prometheus.io/rule: prometheus_http_requests_total,sum by (handler) (prometheus_http_requests_total),prometheus_http_requests_total|component
    prometheus.io/alert: all
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/ey"
  ownerEmail: 
